name: Runnning of ETL project weekly

on: 
    schedule:
        # all monday at 12:00 am to fact historical prices
        - cron: '0 0 * * 1'
jobs:
    run_etl:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.3'
            - name: install dependencies
              run: pip install -r requirements.txt
            
            - name: run pipeline ETL
              run: chmod +x run_etl.sh && ./run_etl.sh 
